import Head from 'next/head'
import Image from 'next/image'
import { useQuery, gql } from '@apollo/client';
import styles from '../styles/Home.module.css'

import { client, countriesClient } from './_app';

const GET_LOCATIONS = gql`
  query GetLocations {
    locations {
      id
      name
      description
      photo
    }
  }
`;

const GET_COUNTRY = gql`
  query Query {
    country(code: "BR") {
      code
      name
    }
  }
`

export default function Home() {
  const { loading, error, data } = useQuery(GET_LOCATIONS, {
    client
  });

  const { loading: countryLoading, error: countryError, data: countryData } = useQuery(GET_COUNTRY, {
    client: countriesClient
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>Apollo Docs Api</h2>

        <div className={styles.grid}>
          {loading && <h2>Loading...</h2>}
          {error && <p>Error: {error.message}</p>}
          {data?.locations?.map(({ code: id, name }: { code: string, name: string }) => (
            <div key={id} className={styles.card}>
              <h4>{name}</h4>
            </div>
          ))}
        </div>

        <h2>Countries Api</h2>

        {countryLoading && <h2>Countries loading...</h2>}
        {countryError && <p>Countries error: {countryError.message}</p>}
        {countryData?.country && <div key={countryData?.country.code} className={styles.card}>
          <h4>{countryData?.country?.name}</h4>
        </div>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
